

> I am a researcher in biostatistics at the [Victorian Centre for Biostatistics](http://www.vicbiostat.org.au), working across [MCRI](https://www.mcri.edu.au/users/margarita-moreno-betancur) and the [University of Melbourne](http://mspgh.unimelb.edu.au/research-groups/centre-for-epidemiology-and-biostatistics-research/biostatistics). I combine methodological research in survival analysis, missing data and causal inference, with collaborative research in various substantive areas, particularly in child and adolescent health. Below you will find a description and resources for selected projects. For other projects see [Scholar](https://scholar.google.com.au/citations?user=aadVh5gAAAAJ&hl=en) and
[GitHub](https://github.com/moreno-betancur).

***

#### Missing data assumptions, sensitivity analyses and causal diagrams

I have long been interested in the development of methods for sensitivity analyses to departures from the "missing at random" (MAR) assumption. What that really meant with multivariable missingness was however difficult to understand, which is why I got interested in causal diagrams as a way to depict missingness assumptions. These have been proposed by Mohan, Pearl and others, and with colleagues we recently constructed canonical diagrams and derived results that will facilitate their application in point-exposure epidemiological studies:

* [Paper in *American Journal of Epidemiology* (open access)](https://academic.oup.com/aje/advance-article/doi/10.1093/aje/kwy173/5074351?searchresult=1)

* Papers on methods for sensitivity analyses to departures from MAR: 
    + Setting with incomplete longitudinal outcomes: [Paper in *SMMR*](http://journals.sagepub.com/doi/abs/10.1177/0962280213490014)
    + Setting with missing cause of failure in survival analysis with competing risks: [Paper in *Biometrics*](https://onlinelibrary.wiley.com/doi/abs/10.1111/biom.12295) 
    + Setting with general multivariable missingness: [Paper in *Statistics in Medicine* (open access)](https://onlinelibrary.wiley.com/doi/full/10.1002/sim.7643) and [R package](https://github.com/moreno-betancur/NARFCS).

***

#### Mediation analysis

For decades researchers have been interested in mediation analysis, which aims to decompose the causal effect of an exposure or treatment on an outcome into its effects via each of multiple pathways. The potential outcomes approach to causal inference has highlighted many difficulties in this endeavour in realistic settings with multiple mediators. Recently, an approach based on "interventional effects" was proposed by Vansteelandt and Daniel (see [here](https://journals.lww.com/epidem/Abstract/2017/03000/Interventional_Effects_for_Mediation_Analysis_with.15.aspx)). In work with my colleague John Carlin we explored the interpretation of these effects, describing hypothetical randomized trials that would enable their estimation:

* [Paper in *Epidemiology*](https://journals.lww.com/epidem/Abstract/2018/09000/Understanding_Interventional_Effects___A_More.3.aspx)

***

#### Understanding variations in disease occurrence across populations

We often wonder the extent to which variations in the distribution of risk factors for a disease explain differences in population measures of incidence or prevalence. With colleagues we formalised this quantitative problem using a causal approach. Thats is, we defined relevant estimands (what do we want to estimate?), assumptions under which these are idenfitiable (when can we estimate these?) and estimators under these assumptions (how can we estimate these?).

* Paper in *International Journal of Epidemiology* (Epub ahead of print 18 Sept 2017): [journal link](https://academic.oup.com/ije/article-abstract/doi/10.1093/ije/dyx194/4161437/Measuring-the-impact-of-differences-in-risk-factor?redirectedFrom=fulltext) and [eAppendix](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/ije/PAP/10.1093_ije_dyx194/1/dyx194_Supp.pdf?Expires=1508324295&Signature=Yn4ELl3~~53U2boyXRDngjzd4okP1cDWGqmpv4NTwN6xgfmTIJ0qnuSG8FrsMluQecp3KKklboBju1rmklm8UUNnJEkpkxN67G3zclDbmdr8neNRJvU1AFntnjzl9EmEml6UyOq6mWaz6rm7z~Sxi7Th4-ZI0ih1UggLjHvUFvgsTJMdm~j3hgdek3f4mj6nRsktnV5Xz0gUhMI4qT3vjT68ffhCHUwy4IomDDSUXDQORufuVtQsJYhwGRdG21yHu7gGX3HL5VZ13soKHRqiQvnbKM0SSupjXY4t3ImYHxMsf8NaCbQD1boEnwOHw4BJWRQ71gd16KUk6LDNQNSU9Q__&Key-Pair-Id=APKAIUCZBIA4LVPAVW3Q).
* [R and Stata code](https://github.com/moreno-betancur/Population_comparisons/archive/master.zip) to apply the methods. 

***

#### Time-dependent covariates in survival analysis

Time-dependent covariates are typically incoporated in hazard rate models using a Last Observation Carried Forward (LOCF) approach, i.e. using the last available measurement as the value of the covariate at each event time. With measurement error or missing data this approach is biased, which has led to the development of joint modelling approaches. We developed a two-stage joint modelling approach called **Multiple Imputation for Joint Modeling (MIJM)** to handle these issues when dealing with multiple continuous markers.

* Paper in *Biostatistics* (Epub ahead of print 12 Oct 2017): [journal link](https://academic.oup.com/biostatistics/article-abstract/doi/10.1093/biostatistics/kxx046/4461848/Survival-analysis-with-time-dependent-covariates?redirectedFrom=fulltext) and [eAppendix](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/biostatistics/PAP/10.1093_biostatistics_kxx046/1/kxx046_Supp.pdf?Expires=1508323179&Signature=B1T3y0Paxl0JvBp8Z0g10ElmkDabUUQnZvs-bgon3bnsQDU8pUyfofiHcfaoRenjK-b5PNtGJcpOKf20hIUgXJoApCBJHFgQicFFq6vMTTCNARGso5cDZAQZYDHHonMj1p4HSh36ojaUqiIvvHRMK2btANWBbyV0zHb29kcQ6QD0xOaN3~tPmXFNoIgBQLNrxEIoaVdZbsFc0d0notf40HuntwrwNR3InLydufetGj1zFpM8tshqxZjsFpK9Pmy-oIyhA~xRVT4BqjwWQHHcOmhXB3l9GBq6SPYE6XeRS77TrAvFWhnyAYjI~r5G5aqSDYwm6Ced54X-ktTwuaUjtg__&Key-Pair-Id=APKAIUCZBIA4LVPAVW3Q)
* [R package 'survtd'](https://github.com/moreno-betancur/survtd): Scroll down the page in the link to learn how to install and use this R package to apply the usual LOCF approach or our approach to incorporate multiple time-dependent covariates in the Cox and additive hazard models.

***

#### Survival analysis with multiple causes of death

With colleagues we developed a model for disease-related mortality that acknowledges that death may be caused by several diseases acting together, by considering all diseases mentioned on the death certificate. We thus obtain estimates of burden-of-disease indicators and epidemiological association parameters that better reflect the contribution of certain diseases (e.g. chronic diseases) to mortality.

* Paper in *Epidemiology* (2017; 28(1): 12-19): [journal link](http://journals.lww.com/epidem/Abstract/2017/01000/Survival_Analysis_with_Multiple_Causes_of_Death_.3.aspx),  [eAppendix](http://download.lww.com/wolterskluwer_vitalstream_com/PermaLink/EDE/B/EDE_2016_06_22_MORENOBETANCUR_15-522_SDC001.pdf) and [video abstract](http://wolterskluwer.http.internapcdn.net/wolterskluwer_vitalstream_com/MP4s/permalink/ede/b/ede_2016_07_15_betancur_15-0522_sdc9.mp4)
* [R package 'survMCOD'](https://github.com/moreno-betancur/survMCOD): Scroll down the page in the link to learn how to install and use this R package to fit Cox models for multiple-cause mortality data using the model proposed in our paper.
* Related papers:
     + [Paper in *Bulletin of the WHO*](http://www.who.int/bulletin/volumes/94/12/16-172189.pdf): Here we build on the same multiple-cause mortality model to calculate cause-related standardized mortality rates from multiple cause-of-death data. The aim is to obtain indicators that better reflect the burden of each disease on mortality.
     + [Paper in *Bulletin épidémiologique hebdomadaire*](http://invs.santepubliquefrance.fr/beh/2017/1/pdf/2017_1_2.pdf)
     + [Commentary by S. Haneuse](http://journals.lww.com/epidem/Citation/2017/01000/Commentary___Multiple_Causes_of_Death__The.5.aspx) on our paper

***

#### Measuring socioeconomic inequalities in health

The Relative Index of Inequality (RII) and the Slope Index of Inequality (SII) are two indices used to measure relative and absolute socioeconomic gradients in health. With colleagues we provided formal definitions for these indices and proposed methods for estimation with individual or aggreated time-to-event data.

* Paper in *Epidemiology* (2015; 26(4):518-527): [pre-print access](http://hdl.handle.net/11343/129569) and [journal link](http://journals.lww.com/epidem/Abstract/2015/07000/Relative_Index_of_Inequality_and_Slope_Index_of.12.aspx) 
* [R code illustration](https://rpubs.com/latoucha/206380) by A. Latouche
* [eAppendix](http://download.lww.com/wolterskluwer_vitalstream_com/PermaLink/EDE/A/EDE_2015_04_01_MORENOBETANCUR_EDE14-467_SDC1.pdf) with R and SAS code.
* [Webinar](https://www.youtube.com/watch?v=S6u3AcrtBuU) at Univ. Aix-Marseille

***





